name: Run Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, macOS 10.15, windows-latest]
        
    steps:
    - uses: actions/checkout@v3
    - name: make test
      run: make test
    - name: run clue
      run: ./clue
